import type { Metadata } from "next";
import { Be_Vietnam_Pro } from "next/font/google";

import Header from "components/Header";

import "./globals.css";

const beVietNamPro = Be_Vietnam_Pro({
  variable: "--font-be-vietnam-pro",
  subsets: ["vietnamese"],
  weight: ["400", "500", "600", "700", "800", "900"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${beVietNamPro.className} antialiased bg-white text-black`}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
